highcharts_port: 8882
rabbit_port: 5673
web_port: 5001
points_generator_port: 5002
pg_port: 5433
redis_port: 6380

initial_highcharts_port: 8080
initial_rabbit_port: 5672
initial_web_port: 8000
initial_points_generator_port: 8000
initial_pg_port: 5432
initial_redis_port: 6379

pg_user: alytics
pg_pass: alytics
pg_url: "postgresql://{{ pg_user }}:{{ pg_pass }}@postgres:{{ initial_pg_port }}/{{ pg_user }}"

rabbit_user: alytics
rabbit_pass: alytics
rabbit_url: "amqp://{{ rabbit_user }}:{{ rabbit_pass }}@rabbit:{{ initial_rabbit_port }}/"

redis_url: "redis://redis:{{ initial_redis_port }}/"

points_generator_url: 'http://points_generator:{{ initial_points_generator_port }}/'
highcharts_url: "http://highcharts:{{ initial_highcharts_port }}/"